(source melpa)
(source gnu)
(source marmalade)

(depends-on "auto-complete")
(depends-on "feature-mode")
(depends-on "grizzl")
(depends-on "ido-vertical-mode")
(depends-on "js2-mode")
(depends-on "projectile")
(depends-on "robe")
(depends-on "web-mode")
(depends-on "yaml-mode")