(source melpa)
(source gnu)
(source marmalade)

(depends-on "auto-complete")
(depends-on "dash-at-point")
(depends-on "enh-ruby-mode")
(depends-on "feature-mode")
(depends-on "flyspell-lazy")
(depends-on "grizzl")
(depends-on "ido-vertical-mode")
(depends-on "js2-mode")
(depends-on "move-text")
(depends-on "projectile")
(depends-on "robe")
(depends-on "web-mode")
(depends-on "yaml-mode")